_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  BACKBONE:
    NAME: "build_coat_fpn_backbone"
  COAT:
    NAME: "coat_lite_mini"
    OUT_FEATURES: ["x1_nocls", "x2_nocls", "x3_nocls", "x4_nocls"]
    WEIGHTS: "../../output/pretrained/coat_lite_mini_6b4a8ae5.pth"
  FPN:
    IN_FEATURES: ["x1_nocls", "x2_nocls", "x3_nocls", "x4_nocls"]
INPUT:
  FORMAT: "RGB"